# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - elixer
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    networks:
      - elixer
  app:
    image: registry.mcd.com/bmcclure89/elixerdemo:latest
    ports:
      - 4040:4040
    networks:
      - elixer
networks:
  elixer:
