# Use postgres/postgres user/password credentials
version: "3.1"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - elixer
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    networks:
      - elixer
  app:
    image: registry.mcd.com/bmcclure89/elixerdemo:latest
    working_dir: /src
    volumes:
      - ./src/hello_pheonix:/src
    ports:
      - 4000:4000
    networks:
      - elixer
networks:
  elixer:
    driver: overlay